[build]
  command = "pip install -r backend/requirements.txt -t backend/lib && npm run build"
  publish = ".next"
  
[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"

[functions.py_api]
  included_files = ["backend/**", "!backend/venv/**", "!backend/__pycache__/**", "!backend/.pytest_cache/**", "!backend/models/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/py_api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
